// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaWeb.API.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NovaWeb.API.Migrations
{
    [DbContext(typeof(NovaWebContext))]
    [Migration("20210226135317_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("NovaWeb.API.Model.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_contato")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("contato");
                });

            modelBuilder.Entity("NovaWeb.API.Model.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_telefone")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("id_contato")
                        .HasColumnType("integer");

                    b.Property<string>("numero")
                        .HasColumnType("text")
                        .HasColumnName("contato");

                    b.HasKey("Id");

                    b.HasIndex("id_contato");

                    b.ToTable("telefone");
                });

            modelBuilder.Entity("NovaWeb.API.Model.Telefone", b =>
                {
                    b.HasOne("NovaWeb.API.Model.Contato", null)
                        .WithMany("telefones")
                        .HasForeignKey("id_contato");
                });

            modelBuilder.Entity("NovaWeb.API.Model.Contato", b =>
                {
                    b.Navigation("telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
