// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaWeb.API.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NovaWeb.API.Migrations
{
    [DbContext(typeof(NovaWebContext))]
    partial class NovaWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("NovaWeb.API.Model.Contato", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id_contato");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("contato");
                });

            modelBuilder.Entity("NovaWeb.API.Model.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_telefone")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("IdContato")
                        .HasColumnType("integer")
                        .HasColumnName("id_contato");

                    b.Property<int?>("contatoId")
                        .HasColumnType("integer");

                    b.Property<string>("numero")
                        .HasColumnType("text")
                        .HasColumnName("contato");

                    b.HasKey("Id");

                    b.HasIndex("contatoId");

                    b.ToTable("telefone");
                });

            modelBuilder.Entity("NovaWeb.API.Model.Contato", b =>
                {
                    b.HasOne("NovaWeb.API.Model.Telefone", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NovaWeb.API.Model.Telefone", b =>
                {
                    b.HasOne("NovaWeb.API.Model.Contato", "contato")
                        .WithMany("telefones")
                        .HasForeignKey("contatoId");

                    b.Navigation("contato");
                });

            modelBuilder.Entity("NovaWeb.API.Model.Contato", b =>
                {
                    b.Navigation("telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
